### ISSUE TITLE
Use Canvas-Sketch

### ISSUE THREAD

**Issue by EkaanshArora** [pranavgoyanka/generative-art#1]
You can use https://github.com/mattdesl/canvas-sketch for better DevEx :)

**Comment by pranavgoyanka** [comment]
Ohh, looks interesting. I was exploring p5js right now, but I'll check this out too :)

**Comment by EkaanshArora** [comment]
haw rude

**Comment by pranavgoyanka** [comment]
lol sorry

**Comment by EkaanshArora** [comment]
assign hacktober i’ll do it for u

**Comment by pranavgoyanka** [comment]
haha, added the hacktoberfest tags. thanks!
